name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '.github/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '.github/**'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running workflow'
        required: false
        default: 'Manual trigger'
        type: string

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - id: check
        name: Check for changes
        run: |
          # Default to false
          echo "should_run=false" >> $GITHUB_OUTPUT
          
          if git diff --quiet HEAD^ HEAD; then
            echo "No changes detected"
          else
            echo "Changes detected"
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check_changes
    if: needs.check_changes.outputs.should_run == 'true'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run a one-line script
      run: echo "Hello from GitHub Actions!"
      
    - name: Run a multi-line script
      run: |
        echo "Starting multi-line script"
        echo "Current date is $(date)"
        echo "Repository: ${{ github.repository }}"
        echo "Trigger reason: ${{ github.event.inputs.reason || 'Automated trigger' }}"
        echo "Workflow complete!"